pipeline {

agent any


stages {


stage('Checkout') {

steps {

git branch: 'develop',
url: 'https://github.com/sravyajavvaji/terraform-eks-jenkins/blob/develop/jenkins/jenkinsfiles'

}

}


stage('Terraform Init') {

steps {

sh 'terraform init'

}

}


stage('Terraform Validate') {

steps {

sh 'terraform validate'

}

}


stage('Terraform Plan') {

steps {

sh 'terraform plan'

}

}


}


}
