name: Terraform Dev


on:

 push:

  branches:

   - develop



jobs:

 terraform:

  runs-on: ubuntu-latest


  steps:

  - name: Checkout

    uses: actions/checkout@v4


  - name: Terraform Setup

    uses: hashicorp/setup-terraform@v3


  - name: Terraform Init

    run:

     terraform init


  - name: Terraform Validate

    run:

     terraform validate
